name: Build-sphinx-docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ development ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
           python-version: "3.10"
        
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build HTML
        run: | 
          cd build/
          make html
      - name: Run ghp-import
        run: | 
          ghp-import -n -p -f build/build/html