name: Check Branch Naming Convention for Development to Staging Branch

on:
  pull_request:
    branches:
      - 'staging'

jobs:
  my_first_job:
    name: Checking if branch origin is development branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check branch name
        run: |
          if [[ "${{ github.head_ref }}" == "development" ]]; then
            echo "Correct origin branch"
          else
            echo "Incorrect origin branch, pull request must go through the development branch before entering the staging branch" 
            exit 1
          fi

  my_second_job:
    name: Checking if branch origin is un-successful
    if: failure()
    runs-on: ubuntu-latest
    needs: my_first_job
    steps:
      - uses: actions/checkout@v4
      - name: Naming convention Failure
        run: echo "Origin branch check failed in previous job"
