name: Development to Staging

on:
  pull_request:
    branches:
      - 'staging'
# This job checks if the branch name is "development" and that it is being merged into "development".
jobs:
  my_first_job:
    name: Is origin development branch?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check branch name
        run: |
          if [[ "${{ github.head_ref }}" == "development" ]]; then
            echo "Correct origin branch"
          else
            echo "Incorrect origin branch, pull request must go through the development branch before entering the staging branch. Please use git commit --allow-empty -m 'Trigger CI' to push and emplty commit which will reset the commit SHA." 
            exit 1
          fi
