name: Check Branch Naming Conventions

on:
  pull_request:
    branches:
      - main

jobs:
  my_first_job:
    name: Checking if branch naming convention is successful
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check branch name
        run: |
          if [[ "${{ github.head_ref }}" == "${{ github.actor }}-"* ]]; then
            echo "Branch has correct naming conventions" ${{ github.head_ref }} ${{ github.actor }}
          else
            echo "Incorrect naming convention, branches must start with username" 
            exit 1
          fi

  my_second_job:
    name: Checking if branch naming convention is un-successful
    if: failure()
    runs-on: ubuntu-latest
    needs: my_first_job
    steps:
      - uses: actions/checkout@v4
      - name: Naming convention Failure
        run: echo "Naming convention check failed in previous job"
